"""add calendar token index

Revision ID: 000b9794afd0
Revises: 5e04dbf30fb0
Create Date: 2020-05-20 14:18:12.644870

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '000b9794afd0'
down_revision = '5e04dbf30fb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_token', 'calendar_tokens', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_token', table_name='calendar_tokens')
    # ### end Alembic commands ###
