"""add calendar token index

Revision ID: 0883574300ef
Revises: 7edc4e5ad74a
Create Date: 2020-05-20 14:19:07.816480

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '0883574300ef'
down_revision = '7edc4e5ad74a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_token', 'calendar_tokens', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_token', table_name='calendar_tokens')
    # ### end Alembic commands ###
