"""first commit for staging

Revision ID: 7edc4e5ad74a
Revises: 
Create Date: 2020-05-17 16:08:46.811853

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '7edc4e5ad74a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_token', table_name='calendar_tokens')
    op.create_index(op.f('ix_simple_passwords_time'), 'simple_passwords', ['time'], unique=False)
    op.drop_index('idx_host_time', table_name='visit_tracks')
    op.create_index('idx_host_time', 'visit_tracks', ['host_id', 'last_visit_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_host_time', table_name='visit_tracks')
    op.create_index('idx_host_time', 'visit_tracks', ['host_id', 'last_visit_time'], unique=True)
    op.drop_index(op.f('ix_simple_passwords_time'), table_name='simple_passwords')
    op.create_index('idx_token', 'calendar_tokens', ['token'], unique=True)
    # ### end Alembic commands ###
